[window]
padding = { x = 8, y = 8}
opacity = 0.75
blur = true
decorations = "Buttonless"
option_as_alt = "Both"

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}

[mouse]
hide_when_typing = true
