[window]
padding = { x = 8, y = 8}
opacity = 1
blur = true
decorations = "Buttonless"
option_as_alt = "Both"

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}

[mouse]
hide_when_typing = true

# Default colors
[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
