# ~/.config/yazi/keymap.toml

[manager]
prepend_keymap = [
    # nvim連携
    { on = ["<Enter>"], run = "open", desc = "既存nvimで開く" },
    { on = ["e"], run = "shell 'zellij run -- nvim \"$@\"' --block --confirm", desc = "新規ペインでnvim" },
    { on = ["E"], run = "shell 'zellij run --floating -- nvim \"$@\"' --block --confirm", desc = "floatingでnvim" },
    
    # 基本操作
    { on = ["l"], run = "plugin --sync smart-enter", desc = "Enter directory or open file" },
    { on = ["h"], run = "leave", desc = "Go back to parent" },
    { on = ["q"], run = "close", desc = "yaziを閉じる" },
    { on = ["<Esc>"], run = "escape", desc = "キャンセル/選択解除" },
    
    # ファイル操作
    { on = ["<Space>"], run = "toggle", desc = "ファイル選択" },
    { on = ["v"], run = "visual_mode", desc = "ビジュアルモード" },
    { on = ["V"], run = "visual_mode --unset", desc = "ビジュアルモード解除" },
    
    # コピー/ペースト/削除
    { on = ["y"], run = "yank", desc = "コピー" },
    { on = ["x"], run = "yank --cut", desc = "カット" },
    { on = ["p"], run = "paste", desc = "ペースト" },
    { on = ["P"], run = "paste --force", desc = "強制ペースト" },
    { on = ["d"], run = "remove", desc = "削除（確認あり）" },
    { on = ["D"], run = "remove --permanently", desc = "完全削除" },
    
    # 作成/リネーム
    { on = ["a"], run = "create", desc = "新規作成" },
    { on = ["r"], run = "rename --cursor=before_ext", desc = "リネーム" },
    
    # 検索・移動
    { on = ["/"], run = "find --smart", desc = "検索" },
    { on = ["f"], run = "plugin fzf", desc = "fzfでジャンプ" },
    { on = ["z"], run = "plugin zoxide", desc = "zoxideでジャンプ" },
    { on = ["g", "g"], run = "arrow -99999999", desc = "先頭へ" },
    { on = ["G"], run = "arrow 99999999", desc = "末尾へ" },
    
    # 表示切り替え
    { on = ["."], run = "hidden toggle", desc = "隠しファイル表示切替" },
    { on = ["s"], run = "search fd", desc = "fd検索" },
    { on = ["S"], run = "search rg", desc = "ripgrep検索" },
    
    # ソート
    { on = ["o", "a"], run = "sort alphabetical --dir-first", desc = "名前順" },
    { on = ["o", "A"], run = "sort alphabetical --reverse --dir-first", desc = "名前順（逆）" },
    { on = ["o", "m"], run = "sort modified --dir-first", desc = "更新日時順" },
    { on = ["o", "M"], run = "sort modified --reverse --dir-first", desc = "更新日時順（逆）" },
    { on = ["o", "s"], run = "sort size --dir-first", desc = "サイズ順" },
    { on = ["o", "S"], run = "sort size --reverse --dir-first", desc = "サイズ順（逆）" },
    
    # タブ操作
    { on = ["t"], run = "tab_create --current", desc = "新規タブ" },
    { on = ["1"], run = "tab_switch 0", desc = "タブ1" },
    { on = ["2"], run = "tab_switch 1", desc = "タブ2" },
    { on = ["3"], run = "tab_switch 2", desc = "タブ3" },
    { on = ["4"], run = "tab_switch 3", desc = "タブ4" },
    { on = ["5"], run = "tab_switch 4", desc = "タブ5" },
    
    # その他
    { on = ["~"], run = "help", desc = "ヘルプ" },
]
