# ~/.config/yazi/yazi.toml

[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""

[opener]
# Enterキー: 既存のnvimで開く（zellijの最後のペインに送る）
edit = [
    { run = '''
        FILE="$@"
        # Zellijで最後に使ったnvimペインにファイルを開くコマンドを送る
        zellij action write-chars ":e $FILE"
        zellij action write 13
        # yaziを閉じる
        zellij action close-pane
    ''', block = false, orphan = true },
]

# eキー: 新規ペインでnvimを開く
open_new = [
    { run = 'zellij run -- nvim "$@"', block = false, orphan = true },
]

# Eキー: floatingペインでnvimを開く
open_floating = [
    { run = 'zellij run --floating -- nvim "$@"', block = false, orphan = true },
]

[open]
rules = [
    { name = "*/", use = "edit" },
    { mime = "text/*", use = "edit" },
    { mime = "inode/x-empty", use = "edit" },
]
